config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
	
	  $routes->addExtensions(['pdf']);
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Tests', 'action' => 'webhooktest']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */ 
    $routes->fallbacks('DashedRoute');
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/ProjectsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Roles
 * @property \Cake\ORM\Association\BelongsTo $Cities
 * @property \Cake\ORM\Association\BelongsTo $States
 * @property \Cake\ORM\Association\BelongsTo $Countries
 *
 * @method \App\Model\Entity\User get($primaryKey, $options = [])
 * @method \App\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\User findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ProjectsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('projects');
        $this->displayField('project_name');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        
        
        $this->belongsTo('Cities', [
            'foreignKey' => 'city_id',
            'joinType' => 'INNER'
        ]);
            $this->hasMany('ProjectUsers', [
            'foreignKey' => 'project_id',
            'joinType' => 'INNER',
           
        ]);
            $this->hasMany('Projectbudgets', [
            'foreignKey' => 'project_id',
            'joinType' => 'INNER',
           
        ]);
        
      /*  $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
           
        ]);*/
         
       $this->belongsTo('Clients', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
            'className'=>'Users'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id', 'ID is required.')
            ->allowEmpty('id', 'create', 'ID cannot be left empty.');

        $validator
            ->requirePresence('project_name', 'create', 'First name is required.')
            ->notEmpty('project_name','First name cannot be left empty.')
            ->add('project_name', 'unique', [
                    'rule' => 'validateUnique',
                    'provider' => 'table',
                    'message' => 'This Project name is already registered. Please add another project name.'
                     ]);

          $validator
            ->requirePresence('manager', 'create', 'Manager is required.')
            ->notEmpty('manager','Manager cannot be left empty.');
            
         $validator
                ->requirePresence('pincode', 'create','Pincode is required .')
                ->notEmpty('pincode','Pincode cannot be left empty .')
                ->numeric('pincode','Please, enter valid pincode .') 
                ->add('pincode', [
                    'length' => [
                        'rule' => ['minLength', 6],
                        'message' => 'The pincode have to be at least 6 digits.',
                    ]
                ])
                ->add('pincode', [
                    'length' => [
                        'rule' => ['maxLength', 6],
                        'message' => 'The pincode have to be maximum 6 digits.',
                    ]
                ]);
       $validator
            ->requirePresence('started_on', 'create', 'Starting date  is required.')
            ->notEmpty('started_on','Starting date cannot be left empty.');
        
        $validator
            ->requirePresence('completed_on', 'create', 'Completion date  is required.')
            ->notEmpty('completed_on','Completion date cannot be left empty.');
            
        $validator
            ->requirePresence('estimated_budget', 'create','Estimated budget  is required.')
            ->notEmpty('estimated_budget','Estimated budget cannot be left empty.');
            
             $validator
            ->requirePresence('approved_budget', 'create','Approved budget  is required.')
            ->notEmpty('approved_budget','Approved budget cannot be left empty.');
        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['projectname']));
       
        $rules->add($rules->existsIn(['city_id'], 'Cities'));
     
        return $rules;
    }
}

src/Template/Projects/client_projects.ctp
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<div class="breadcrumbs">
    <ol class="breadcrumb">
        <li>
           Projects
        </li>
        <li class="active">All Projects</li>
    </ol>
</div>

   <div class="col-md-12">
        <?php echo $this->Flash->render(); ?>

        <div class="portlet portlet box red" > 
            <div class="portlet-title">
                <div class="caption mil1">
                    <i class="fa fa-area-chart"></i><?php echo __('All Projects') ?> </div>
                 <div class="actions">
                 </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-advance " id="projects">
                        <thead>
                            <tr>

                                <th><?php echo __('Project Name'); ?></th>
                                <th><?php echo __('Client'); ?></th>
                                <th><?php echo __('Country'); ?></th>
                                <th><?php echo __('state'); ?></th>
                                <th><?php echo __('city'); ?></th>
                                <th><?php echo __('Pincode'); ?></th>
                                <th><?php echo __('Started on'); ?></th>
                                <th><?php echo __('Completion Date'); ?></th>
                                <th><?php echo __('Estimated Budjet'); ?></th>
                                <th><?php echo __('Approved Budget'); ?></th>
                                <th><?php echo __('Actions'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan='11' align='center'> <?php echo __('Loading'); ?> </td>
                            </tr>
                        </tbody>
                    </table>
                </div>	
            </div>
        </div>    
    </div>
       
  <div id="model" class="modal fade  bs-modal-lg" aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
           <div class="modal-header">
                <button class="close" aria-hidden="true" data-dismiss="modal" type="button"><i class="fa  fa-times "></i></button>
            </div>
            <div class="modal-body">               
                <div id="ErrorDiv1" class="message error" style="display:none;"><span id="ErrorMsg1"></span></div>
                <div id="SuccessDiv1" class="message success" style="display:none;"><span id="SuccessMsg1"></span></div>
                <div id="details">

                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->Html->script('../DATATABLE_BUTTON/jquery.dataTables.min.js'); ?>
<?php echo $this->Html->css('../DATATABLE_BUTTON/jquery.dataTables.min.css'); ?>
<script>
    $('document').ready(function () {
        createTable();
        
    });
    function createTable() {
        $('#projects').dataTable({
            "bProcessing": false,
            "bServerSide": true,
            "bDestroy": true,
           "sAjaxSource": "<?php echo $this->Url->build(['controller' => 'Projects', 'action' => 'getClientProjects']); ?>",
            "columnDefs": [{"className": "dt-center", "targets": "_all"},
                {
                    "targets": 10,
                    "data": function (row, type, val, meta) {
						str = "<a class='label label-sm label-success' href='javascript:;' onclick=openViewModal('" + row[10] + "')>View</a>";
						
						str += "&nbsp;<a class='label label-sm label-info' href='javascript:;' onclick=openViewLedgerModal('" + row[10] + "')>Ledger</a>";
						
						
						return str;
						
						
                       
                    }
                }
            ]
            
        });
    }
      function openViewModal(id) {
	    $('#SuccessDiv1').hide();
        $('#ErrorDiv1').hide();

        $.blockUI({
            message: '<h3>Loading</h3>',
            css: {
                border: 'none',
                padding: '8px',
                backgroundColor: '#000',
                '-webkit-border-radius': '10px',
                '-moz-border-radius': '10px',
                opacity: .5,
                color: '#fff'
            }
        });
        $.ajax({
            url: "<?php echo $this->Url->build(['controller' => 'Projects', 'action' => 'view']); ?>/" + id,
            success: function (rsp) {
                $("#details").empty();
                $("#details").append(rsp);
                $('#model').modal('show');
                $.unblockUI();
            }
        });
    }
    
      function openViewLedgerModal(id) {
        $('#SuccessDiv1').hide();
        $('#ErrorDiv1').hide();

        $.blockUI({
            message: '<h3>Loading</h3>',
            css: {
                border: 'none',
                padding: '8px',
                backgroundColor: '#000',
                '-webkit-border-radius': '10px',
                '-moz-border-radius': '10px',
                opacity: .5,
                color: '#fff'
            }
        });
        $.ajax({
            url: "<?php echo $this->Url->build(['controller' => 'Ledgers', 'action' => 'getledger']); ?>/" + id,
            success: function (rsp) {
                $("#details").empty();
                $("#details").append(rsp);
                $('#model').modal('show');
                $.unblockUI();
            }
        });
    }
    
    
</script>

src/Template/Projects/manager_all_projects.ctp
  <?php// debug($id);?> 
        
        <div class="portlet portlet box red" > 
            <div class="portlet-title">
                <div class="caption mil1">
                    <i class="fa fa-area-chart"></i><?php echo __('All Projects') ?> </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-advance " id="projects">
                        <thead>
                            <tr>

                                <th><?php echo __('Project Name'); ?></th>
                                <th><?php echo __('Client'); ?></th>
                                <th><?php echo __('Country'); ?></th>
                                <th><?php echo __('state'); ?></th>
                                <th><?php echo __('city'); ?></th>
                                <th><?php echo __('Pincode'); ?></th>
                                 <th><?php echo __('Started on'); ?></th>
                                <th><?php echo __('Completion Date'); ?></th>
                                <th><?php echo __('Estimated Budget'); ?></th>
                                <th><?php echo __('Approved Budget'); ?></th>
                                 
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan='9' align='center'> <?php echo __('Loading'); ?> </td>
                            </tr>
                        </tbody>
                    </table>
                </div>	
            </div>
        </div>    
   
       
 

<script>
    $('document').ready(function () {
		userId='<?php echo $id ?>';
		//alert(userId);
		
        createTable();
        
    });
    function createTable() {
        $('#projects').dataTable({
            "bProcessing": false,
            "bServerSide": true,
            "bDestroy": true,
           "sAjaxSource": "<?php echo $this->Url->build(['controller' => 'Projects', 'action' => 'getManagerAllProjects']); ?>/"+userId,
            "columnDefs": [{"className": "dt-center", "targets": "_all"},
                {
                   
                }
            ]
            
        });
    }
      
     
   
     
 
   
</script>

src/Template/Projects/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<div class="breadcrumbs">
    <ol class="breadcrumb">
        <li>
           Projects
        </li>
        <li class="active">View Projects</li>
    </ol>
</div>
<?php //debug($project->id);  ?>
<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
             <i class="fa fa-area-chart"></i>Projects Details</div>
         <?php if($this->request->session()->read('Auth.User.role_id')==1){?>  
        <div class="actions"> <a href="javascript:;" class="btn blue-madison" onClick="viewBudget(<?php echo $project->id;  ?>);">
                  View Budget Details</a> </div>
           <?php } else { ?><div class="actions"> <a href="javascript:;" class="btn blue-madison" onClick="viewProjectBudget(<?php echo $project->id;  ?>);">
                  View Budget Details</a> </div> <?php } ?>

    </div>
    <div class="portlet-body form">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <?php //debug($project);?>
                    <tbody>
                            <tr>
                                <th> Project Name</th>
                                <td> <?php echo $project->project_name ?></td>
                            </tr>

                           <tr>
                                <th> Manager </th>
                                <td> <?php foreach($project->project_users as $user):?>
                                         <?= $user->user->first_name." ".$user->user->last_name."," ?>  
                                         <?php endforeach;?>
                                </td>
                            </tr>

                           <tr>
                                <th> Client </th>
                                <td> <?php echo $project->client->first_name." ".$project->client->last_name ?>  </td>
                            </tr>
                            
                           <tr>
                                <th> Country </th>
                                <td> <?php echo $project->city->state->country->country_name ?>  </td>
                            </tr>

                            <tr>
                                <th> State</th>
                                  <td> <?php echo $project->city->state->state_name ?>  </td>
                            </tr>

                            <tr>
                                <th> city </th>
                               <td> <?php echo $project->city->city_name ?>  </td>
                            </tr>

                            <tr>
                                <th> pincode</th>
                                <td> <?php echo $project->pincode ?> </td>
                            </tr>
                            <tr>
                                <th> Started On</th>
                                <td><?php echo $project->started_on ?>  </td>
                            </tr>
                            <tr>
                                <th> Completion Date</th>
                                <td><?php echo $project->completed_on ?>  </td>
                            </tr>
                            <tr>
                                <th> Estimated Budget</th>
                               <td><?php echo $project->estimated_budget ?>  </td>
                            </tr>

                            <tr>
                                <th> Approved Budget</th>
                                <td><?php echo $project->approved_budget ?>  </td>
                            </tr>
                            <tr>
                                <th> Total Payment Recieved</th>
                                <td><?php echo $paymentsum ?>  </td>
                            </tr>
                   </tbody>
            </table>
        </div>

    </div>
</div>

 <div class="portlet box blue" style="display:none;" id="budgetbox"> 
            <div class="portlet-title">
                <div class="caption">
                  <i class="fa fa-area-chart "></i>Projects Budget Details</div>
                <div class="actions"> <a href="javascript:;" class="btn yellow-crusta" onClick="openBudgetModal(<?php echo $project->id;  ?>);">
                   Assign Budget</a> </div>
             </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-advance " id="budgetdetails" style="width: 100%;">
                        <thead>
                            <tr>
                                <th><?php echo __('Amount'); ?></th>
                                <th><?php echo __('Alloted By'); ?></th>
                                <th><?php echo __('Alloted To'); ?></th>
                                <th><?php echo __('Alloted On'); ?></th>      
                                <th><?php echo __('Actions'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan='5' align='center'> <?php echo __('Loading'); ?> </td>
                            </tr>
                        </tbody>
                    </table>
                </div>	
            </div>
   </div>  


<div class="portlet box blue" style="display:none;" id="managerbudgetbox">
            <div class="portlet-title">
                <div class="caption">
                  <i class="fa fa-user"></i>Projects Budget Details</div>
                
             </div>
            <div class="portlet-body">
                <div class="table-responsive">
                     <table class="table table-striped table-bordered table-advance " id="Managerbudgetdetails" style="width: 100%;">
                        <thead>
                            <tr>
                                <th><?php echo __('Amount'); ?></th>
                                <th><?php echo __('Alloted By'); ?></th>
                                <th><?php echo __('Alloted To'); ?></th>
                                <th><?php echo __('Alloted On'); ?></th>      
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan='5' align='center'> <?php echo __('Loading'); ?> </td>
                            </tr>
                        </tbody>
                    </table>
                </div>	
            </div>
   </div>  


<script>
    function viewBudget(id) {
		
         $('#budgetdetails').dataTable({
            "bProcessing": false,
            "bServerSide": true,
            "bDestroy": true,
            "sAjaxSource": "<?php echo $this->Url->build(['controller' => 'ProjectBudgets', 'action' => 'index1']); ?>/" + id,
            "columnDefs": [{"className": "dt-center", "targets": "_all"},
                {
                    "targets": 4,
                    "data": function (row, type, val, meta) {
						
						str1 = "&nbsp;<a class='label label-sm label-info' href='javascript:;' onclick=openBudgetEditModal('" + row[4] + "')>edit</a>";
//						str1 += "&nbsp;<a class='label label-sm label-danger' href='javascript:;' onclick=openDeleteModal('" + row[3] + "')>Delete</a>";
						str1 += "&nbsp;<a class='label label-sm label-success'  href='/ProjectBudgets/invoice.pdf?BudgetID=" + row[4] + "'>Generate Budget Invoice</a>"
						return str1;
			
                    }
                }
            ]
            
        });
        $('#budgetbox').toggle();
        }
        
         function viewProjectBudget(id) {

         $('#Managerbudgetdetails').dataTable({
            "bProcessing": false,
            "bServerSide": true,
            "bDestroy": true,
            "sAjaxSource": "<?php echo $this->Url->build(['controller' => 'ProjectBudgets', 'action' => 'index1']); ?>/" + id,
            "columnDefs": [{"className": "dt-center", "targets": "_all"},
                {
                    
                }
            ]
            
        });
        $('#managerbudgetbox').toggle();
        }
        
        function openBudgetEditModal(id) {
			projectId='<?php echo $project->id;  ?>';
		//alert(projectId);
	    $('#SuccessDiv1').hide();
        $('#ErrorDiv1').hide();

        $.blockUI({
            message: '<h3>Loading</h3>',
            css: {
                border: 'none',
                padding: '8px',
                backgroundColor: '#000',
                '-webkit-border-radius': '10px',
                '-moz-border-radius': '10px',
                opacity: .5,
                color: '#fff'
            }
        });
        $.ajax({
            url: "<?php echo $this->Url->build(['controller' => 'ProjectBudgets', 'action' => 'edit']); ?>/" + id+'/'+projectId,
            success: function (rsp) {
                $("#details").empty();
                $("#details").append(rsp);
                $('#model').modal('show');
                $.unblockUI();
            }
        });
    }
         function openDeleteModal(id) {
	     $('#SuccessDiv1').hide();
         $('#ErrorDiv1').hide();

         $.ajax({
                type: "POST",
                url: "<?php echo $this->Url->build(['controller' => 'ProjectBudgets', 'action' => 'delete']); ?>/"+id,
               
                success: function (data) {
                    data = jQuery.parseJSON(data);
                    if (data.success == false) {
                        $('#ErrorDiv1').show();
                        $('#ErrorMsg1').html(data.message);

                    } else {

                        $('#SuccessDiv1').show();
                        $('#SuccessMsg1').html(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 2000);
                    }
                }
            });
    }
    
    </script>